echo '[build]
  base = "robert"
  command = "npm run build"
  publish = "build"

[context.production.environment]
  REACT_APP_ENV = "production"' > netlify.toml.new

# Reemplaza el archivo original
mv netlify.toml.new netlify.toml